import pandas as pd 
df = pd.read_csv(r"C:\Users\VSIT\Documents\students.csv")
print(f"First 5 rows")
print(df.head(5))
rows, cols = df.shape
print(f"\n---------Number of Rows and Columns---------\n")
print(f"Number of rows: {rows}, number of columns: {cols}")
print(f"\n---------Name and GPA of students---------\n")
print(df[['name', 'GPA']])
print(f"\n---------Students with GPA >= 3.5---------\n")
high_gpa = df[df["GPA"] >= 3.5]
print(high_gpa)
print(f"\n---------Students by GPA---------\n")
sort_gpa = df.sort_values(by="GPA", ascending=False)
print(sort_gpa)
print(f"\n--------Average GPA by Major-------\n")
print(df.groupby("major")["GPA"].mean())

import pandas as pd
students = pd.read_csv(r"C:\Users\VSIT\Documents\students.csv")
scores = pd.read_csv(r"C:\Users\VSIT\Documents\scores.csv")
missing_students = students.isnull().sum()
missing_scores = scores.isnull().sum()
print(f"\n---------Missing Values in Students DataFrame---------")
print(missing_students)
print(f"\n---------Missing Values in Scores DataFrame---------")
print(missing_scores)
students_missing = students.dropna(subset=['student_id'])
GPA_missing = students.dropna(subset=['GPA'])
scores_missing = scores.fillna(scores.mean(numeric_only=True))
print(f"\n---------Students DataFrame after dropping rows with missing student_id---------")
print(students_missing)
print(f"\n---------GPA DataFrame after dropping rows with missing GPA---------")
print(GPA_missing)
print(f"\n---------Scores DataFrame after filling missing values with mean---------")
print(scores_missing.round(2))
merge = pd.merge(students_missing, scores_missing, on='student_id', how='inner')
print(f"---------Merged DataFrame---------\n{merge.round(2)}")
students_avg = merge.groupby('student_id').mean(numeric_only=True).reset_index()
score_columns = ['python','math','database']
students_avg['average_score'] = students_avg[score_columns].mean(axis=1)
print(f"\n---------Average Scores by Student ID with Average Column---------\n{students_avg.round(2)}")
print(f"\n---------Average Scores by Student ID---------\n{students_avg.round(2)}")
top_5 = students_avg.sort_values(by='average_score', ascending=False).head(5)
print(f"\n---------Top 5 Students by Average Score---------\n{top_5.round(2)}")
major_avg = merge.groupby('major').mean(numeric_only=True).reset_index()
print(f"\n---------Average Scores by Major---------\n{major_avg.drop(columns = ['age']).round(2)}")